env:
  node: true,
  es2021: true
extends:
  - eslint:recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
globals:
  Omegga: readonly
  VERBOSE: readonly
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
