env:
  node: true,
  es2021: true
extends:
  - eslint:recommended
parser: "@babel/eslint-parser"
plugins: [prettier]
parserOptions:
  ecmaVersion: 12
  requireConfigFile: false
globals:
  Omegga: readonly
  VERBOSE: readonly
rules:
  prettier/prettier: warn
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
